services:
  db:
    build:
      context: ./db
    env_file:
      - .env.sample
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "sh", "check_service.sh"]
      interval: 5s
      retries: 5
      timeout: 3s
      start_period: 10s

  core:
    build:
      context: ./app
    env_file:
      - .env.sample
    volumes:
      - ./app:/usr/local/app
    depends_on:
      db:
        condition: service_healthy
    command: ["uv", "run", "python", "main.py"]
